# permissions for end users to edit checkers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-istio-checker
    app.kubernetes.io/managed-by: kustomize
  name: checker-editor-role
rules:
- apiGroups:
  - checker.depishev
  resources:
  - checkers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - checker.depishev
  resources:
  - checkers/status
  verbs:
  - get
