apiVersion: checkers.checker.depishev/v1 # Пишет Error: no matches for Id Checker.v1.checker.depishev/checker-istio.[noNs]; failed to find unique target for patch Checker.v1.checker.depishev/checker-istio.[noNs]
#проверить конфигмапу UPD. Берется не отсюда. -> Смотреть samples checker_v1_checker.yaml и kustomization.yaml
kind: Checker
metadata:
  labels:
    app.kubernetes.io/name: checker-istio
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: checker-istio
  name: checker-istio
spec:
  destinationNamespaces: ["production", "development"] # подумать как передавать переменную. ENV?
  sourceNamespaces: ["production", "development"] # подумать как передавать переменную. ENV?
  externalIPtoCheck: ["production", "development"] # подумать как передавать переменную. ENV?